POST https://node-do-zero-lfb0.onrender.com/videos
Content-Type: application/json
 
{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###
GET https://node-do-zero-lfb0.onrender.com/videos

###
PUT https://node-do-zero-lfb0.onrender.com/videos/1be17bb4-2a3a-45b1-a89b-f50e18c44d7c
Content-Type: application/json
 
{
    "title": "Video 01",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###
DELETE https://node-do-zero-lfb0.onrender.com//videos/1be17bb4-2a3a-45b1-a89b-f50e18c44d7c